-- !Ups

ALTER TABLE heroes
ADD COLUMN weapon INT DEFAULT NULL REFERENCES inventories ON DELETE SET NULL,
ADD COLUMN armor INT DEFAULT NULL REFERENCES inventories ON DELETE SET NULL,
ADD COLUMN accessory INT DEFAULT NULL REFERENCES inventories ON DELETE SET NULL;

-- !Downs

ALTER TABLE heroes
DROP COLUMN weapon,
DROP COLUMN armor,
DROP COLUMN accessory;